# Generated by Django 5.0.2 on 2024-03-04 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(max_length=50)),
                ('price', models.FloatField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Predictions',
            },
        ),
    ]
